---
- hosts: wordpress
  sudo: yes

  roles:
    - common
    - base/mysql
    - base/nginx
    - apps/wordpress
    - vendor/role-hardening

    - role: apps/migration
      when: migration is defined
